[package]
name = "rust-amethyst-pong"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2018"


[dependencies]
amethyst = "0.13.2"
log = { version = "0.4.8", features = ["serde"] }
objc = "=0.2.6"


[features]
default = ["metal"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
nightly = ["amethyst/nightly"]
